apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-sit
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kirkchen/argocd-helm-prometheus-poc
    targetRevision: HEAD
    path: kube-prometheus-stack/base
    helm:
      valueFiles:
        - values.yaml
        - ../overlays/sit/values.yaml
      skipCrds: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-sit
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - CreateCustomResourceDefinitions=true
      - ServerSideApply=true
