kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      retention: 15d
      resources:
        requests:
          cpu: 500m
          memory: 2Gi
        limits:
          cpu: 1000m
          memory: 4Gi
